{
    "Message": "Download in progress...",
    "CompletionMessage": "Download Successful",
    "CompletionTimeout": 7,
    "OnSuccess": "/deeplinktomdkapp/Actions/com_bccd_ewm/Service/DownloadOffline.action",
    "_Type": "Action.Type.ProgressBanner"
}